title: Jean de Dieu Nyandwi
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
#  skin: dark
  social_links:
    twitter: Jeande_d
    github:  Nyandwi
    linkedin: nyandwi
    instagram: jeande_de
    youtube_channel: UCSPFIgLyc2t-pNim-CdyBNQ
    youtube_channel_name: Jean de Dieu Nyandwi
google_analytics: G-W0PE5HT9JD
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
