title: Jean de Dieu Nyandwi
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: Jeande_d
    github:  Nyandwi
    linkedin: nyandwi
    medium: jeande
    youtube_channel: UCRUFwFhet7BmEojTpbfkenA
    youtube_channel_name: Deep Learning Revision
google_analytics: 
highlighter: rouge
kramdown:
    math_engine: katex
    syntax_highlighter: rouge
