project:
  type: website
  output-dir: docs

website:
  site-url: nyandwi.com
  title: "Personal Webpage"
  favicon: extras/cmu_favicon_32x32.png
  search: false
  google-analytics: "G-W0PE5HT9JD"
  navbar:
    right:
      # - text: "About"
      #   href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Misc"
        href: misc.qmd
      - icon: github
        href: https://github.com/Nyandwi
      - icon: twitter
        href: https://twitter.com/jeande_d
      - icon: linkedin
        href: https://www.linkedin.com/in/nyandwi/
format:
  html:
    theme: cosmo
    css: styles.css



