---
title: "Non-technical notes"
toc: false
---

I have been yearning a lot about writing things that are not related to technical topics. There are times ideas sparks and either end up on social media status(which is not the right medium of sharing ideas, also hard to resist attention seeking that comes with it), my internal private notes, or simply life happens and I move on. And again and again.

So I am trying this new things where I write about whatever comes on my mind without the fear of judgment that comes with sharing one's mind online. The vast majority of people follow me for technical things and I do not think anyone will see this(if you do, ping me on X and I will update this page).

The posts are really my notes or things I do want to read. They should be small and I am not going to spend a huge chunk of time on writing this as I have bigger topics on the other side. This really is to capture serendipitous moments while they are still alive. I have noticed that when I am happy, my mind subconsciously generates things. This is a place for those things. Low commitment, short, and one theme. Let's gooo!!
